export const HOLD_REASONS = [
  'Customs inspection required',
  'Clearance delay — additional documents needed',
  'Restricted or prohibited item review',
  'Incorrect or incomplete address',
  'Recipient not available',
  'No one home to sign for delivery',
  'Business closed at time of delivery',
  'Delivery attempted — access issue',
  'Payment or duties pending',
  'COD or postage due',
  'Weather or operational delay',
  'Vehicle breakdown or mechanical delay',
  'Network congestion at sort facility',
  'Missed sort / late arrival at hub',
  'Package damaged — inspection needed',
  'Suspected damaged or leaking contents',
  'Security or contents screening',
  'Weight or dimension discrepancy',
  'Held at location by recipient request',
  'Held at location by shipper request',
  'Vacation hold',
  'Redirect requested — waiting for new address',
  'Local holiday — no delivery today',
  'Address change pending verification',
  'Adult signature required — ID not presented',
  'Other',
];
